module.exports = ({
        MBTI: [
            "INFP",
            "INFJ",
            "ENFP",
            "ENFJ",
            "INTJ",
            "INTP",
            "ENTP",
            "ENTJ",
            "ISFP",
            "ISFJ",
            "ESFP",
            "ESFJ",
            "ISTP",
            "ISTJ",
            "ESTP",
            "ESTJ"
        ],
        Enneagram: [
            "1w2",
            "2w3",
            "3w2",
            "3w4",
            "4w3",
            "4w5",
            "5w4",
            "5w6",
            "6w5",
            "6w7",
            "7w6",
            "7w8",
            "8w7",
            "8w9",
            "9w8",
            "9w1"
        ],
        Zodiac: [
            "Aries",
            "Taurus",
            "Gemini",
            "Cancer",
            "Leo",
            "Virgo",
            "Libra",
            "Scorpio",
            "Sagittarius",
            "Capricorn",
            "Aquarius",
            "Pisces"
        ]
    }
);